// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WEB_API_1_Paskaita.DataBase;

#nullable disable

namespace WEB_API_1_Paskaita.Migrations
{
    [DbContext(typeof(AplicationDbContext))]
    [Migration("20240729163738_addAccount")]
    partial class addAccount
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WEB_API_1_Paskaita.Models.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Password")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("WEB_API_1_Paskaita.Models.Contact", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Company")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Mail")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Note")
                        .HasMaxLength(8000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Contacts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Company = "DAART15",
                            CreatedAt = new DateTime(2024, 7, 29, 19, 37, 38, 76, DateTimeKind.Local).AddTicks(6095),
                            FirstName = "Ramas",
                            LastName = "Darr",
                            Mail = "ramas@daart15.com",
                            Note = "mano kontaktas",
                            PhoneNumber = "+37023456789",
                            UpdatedAt = new DateTime(2024, 7, 29, 19, 37, 38, 76, DateTimeKind.Local).AddTicks(6138)
                        },
                        new
                        {
                            Id = 2,
                            Company = "UAB Tadilis",
                            CreatedAt = new DateTime(2024, 7, 29, 19, 37, 38, 76, DateTimeKind.Local).AddTicks(6140),
                            FirstName = "Tadas",
                            LastName = "Tadulis",
                            Mail = "tadas@tadulis.com",
                            Note = "",
                            PhoneNumber = "+370234",
                            UpdatedAt = new DateTime(2024, 7, 29, 19, 37, 38, 76, DateTimeKind.Local).AddTicks(6141)
                        },
                        new
                        {
                            Id = 3,
                            Company = "DAART15",
                            CreatedAt = new DateTime(2024, 7, 29, 19, 37, 38, 76, DateTimeKind.Local).AddTicks(6142),
                            FirstName = "Andius",
                            LastName = "Daar",
                            Mail = "andriusl@daart15.com",
                            Note = "vyr. kontaktas",
                            PhoneNumber = "+37023456799",
                            UpdatedAt = new DateTime(2024, 7, 29, 19, 37, 38, 76, DateTimeKind.Local).AddTicks(6143)
                        },
                        new
                        {
                            Id = 4,
                            Company = "DAART15",
                            CreatedAt = new DateTime(2024, 7, 29, 19, 37, 38, 76, DateTimeKind.Local).AddTicks(6144),
                            FirstName = "Arma",
                            LastName = "Daar",
                            Mail = "arma@daart15.com",
                            Note = "junior kontaktas",
                            PhoneNumber = "+37023456788",
                            UpdatedAt = new DateTime(2024, 7, 29, 19, 37, 38, 76, DateTimeKind.Local).AddTicks(6145)
                        },
                        new
                        {
                            Id = 5,
                            Company = "DAART15",
                            CreatedAt = new DateTime(2024, 7, 29, 19, 37, 38, 76, DateTimeKind.Local).AddTicks(6146),
                            FirstName = "Daiva",
                            LastName = "Darr",
                            Mail = "daiva@daart15.com",
                            Note = "paciausias kontaktas",
                            PhoneNumber = "+3702345639",
                            UpdatedAt = new DateTime(2024, 7, 29, 19, 37, 38, 76, DateTimeKind.Local).AddTicks(6147)
                        });
                });

            modelBuilder.Entity("WEB_API_1_Paskaita.Models.SafetyCar", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SafetyCars", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Aston Martin",
                            Color = "Green Metalic",
                            Model = "Vantage"
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Mercedes-Benz",
                            Color = "Black",
                            Model = "AMG GT Black Series"
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Mercedes-Benz",
                            Color = "Silver",
                            Model = "AMG GT R"
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Lamborghini",
                            Color = "Red",
                            Model = "Diablo"
                        });
                });

            modelBuilder.Entity("WEB_API_1_Paskaita.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("bcfdb5b6-df09-4242-96d4-5bb16b21fa1a"),
                            City = "New York",
                            CreationDateTime = new DateTime(2024, 7, 29, 16, 37, 38, 76, DateTimeKind.Utc).AddTicks(4834),
                            Email = "johndoe@example.com",
                            UserName = "JohnDoe"
                        },
                        new
                        {
                            Id = new Guid("da7c7f4f-dd76-4b55-9b52-6755caaf4ac2"),
                            City = "Los Angeles",
                            CreationDateTime = new DateTime(2024, 7, 29, 16, 37, 38, 76, DateTimeKind.Utc).AddTicks(4846),
                            Email = "janedoe@example.com",
                            UserName = "JaneDoe"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
