// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WEB_API_1_Paskaita.DataBase;

#nullable disable

namespace WEB_API_1_Paskaita.Migrations
{
    [DbContext(typeof(AplicationDbContext))]
    partial class FoodDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WEB_API_1_Paskaita.Models.SafetyCar", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SafetyCars", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Aston Martin",
                            Color = "Green Metalic",
                            Model = "Vantage"
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Mercedes-Benz",
                            Color = "Black",
                            Model = "AMG GT Black Series"
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Mercedes-Benz",
                            Color = "Silver",
                            Model = "AMG GT R"
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Lamborghini",
                            Color = "Red",
                            Model = "Diablo"
                        });
                });

            modelBuilder.Entity("WEB_API_1_Paskaita.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("686bbd3f-17e2-46b1-8162-a2fb20e514c2"),
                            City = "New York",
                            CreationDateTime = new DateTime(2024, 7, 16, 19, 38, 32, 517, DateTimeKind.Utc).AddTicks(7107),
                            Email = "johndoe@example.com",
                            UserName = "JohnDoe"
                        },
                        new
                        {
                            Id = new Guid("7202316e-cc60-4c98-9bee-03c0a964fe3e"),
                            City = "Los Angeles",
                            CreationDateTime = new DateTime(2024, 7, 16, 19, 38, 32, 517, DateTimeKind.Utc).AddTicks(7126),
                            Email = "janedoe@example.com",
                            UserName = "JaneDoe"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
